select
OS.CUSTOMERID,
C.CUSTOMERNAME,
SUM(OS.ORDERCOUNT) as ORDERCOUNT,
sum(OS.REVENUE) AS REVENUE
FROM   
    {{ref("order_fact") }} OS
JOIN
    {{ref("customer_stg") }} C ON OS.CUSTOMERID = C.CUSTOMERID
GROUP BY
OS.CUSTOMERID,
C.CUSTOMERNAME