select
ORDERID, 
ORDERDATE, 
CUSTOMERID, 
EMPLOYEEID, 
STOREID, 
STATUS as STATUSCD,
CASE 
    WHEN STATUS = '01' THEN 'IN PROGRESS'
    WHEN STATUS = '02' THEN 'COMPLETED'
    WHEN STATUS = '03' THEN 'CANCELLED'
    ELSE null
END AS STATUSDESC,
CASE
    WHEN STOREID = 1000 THEN 'ONLINE'
    ELSE 'IN STORE'
END AS ORDER_CHANNEL,
UPDATED_AT,
CURRENT_TIMESTAMP AS DBT_UPDATE_AT

FROM
    {{ source("landing", 'orders')}}